apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-agent
  namespace: example-namespaced
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitops-agent
  namespace: example-namespaced
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-agent
  namespace: example-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-agent
subjects:
  - kind: ServiceAccount
    name: gitops-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-agent
  namespace: example-namespaced
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gitops-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitops-agent
    spec:
      containers:
        - image: argoproj/gitops-agent:latest
          name: gitops-agent
          command:
            - gitops
            - /tmp/git/repo
            - --path
            - ch09/namespaced/example
            - --namespaced
          volumeMounts:
            - mountPath: /tmp/git
              name: git
        - image: k8s.gcr.io/git-sync:v3.1.6
          name: git-sync
          args:
            - --webhook-url
            - http://localhost:9001/api/v1/sync
            - --dest
            - repo
            - --branch
            - main
          env:
            - name: GIT_SYNC_REPO
              value: https://github.com/PacktPublishing/ArgoCD-in-Practice
          volumeMounts:
            - mountPath: /tmp/git
              name: git
      serviceAccountName: gitops-agent
      volumes:
        - emptyDir: {}
          name: git
